//Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';


//Password Reset
export const  FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const  RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const LOAD_USERS = 'LOAD_USERS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const USERS_ERROR = 'USERS_ERROR';

export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';



//General
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_ERROR = 'SET_ERROR';


// Chat Types
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';
export const CLEAR_ACTIVE_CHAT = 'CLEAR_ACTIVE_CHAT';
export const LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const MARK_MESSAGES_READ = 'MARK_MESSAGES_READ';
export const SET_TYPING = 'SET_TYPING';
export const CLEAR_TYPING = 'CLEAR_TYPING';
export const UPDATE_ONLINE_USERS = 'UPDATE_ONLINE_USERS';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';
export const CHAT_ERROR = 'CHAT_ERROR';
export const CLEAR_CHAT_ERRORS = 'CLEAR_CHAT_ERRORS';

